// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVUnIyZuFhetEDRmAK_Cw9VBK_r3adExA',
    appId: '1:623278585949:web:c2da5d70dea2854ea4b5b4',
    messagingSenderId: '623278585949',
    projectId: 'livetips-app',
    authDomain: 'livetips-app.firebaseapp.com',
    storageBucket: 'livetips-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLRImKreMz3FAGpiTPnY0qWbHVowb1FM',
    appId: '1:623278585949:android:a06c7b108ab6aa18a4b5b4',
    messagingSenderId: '623278585949',
    projectId: 'livetips-app',
    storageBucket: 'livetips-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfL3nmowibt-FefYeIsuTZsmlaBOyLXbY',
    appId: '1:623278585949:ios:c73a48a4b09f7eaba4b5b4',
    messagingSenderId: '623278585949',
    projectId: 'livetips-app',
    storageBucket: 'livetips-app.firebasestorage.app',
    androidClientId: '623278585949-3p9pa5g2d4tpshm03vt92bjma7min498.apps.googleusercontent.com',
    iosClientId: '623278585949-pgjt0cu5dpo4nlomoujunmlcrn954av7.apps.googleusercontent.com',
    iosBundleId: 'com.mekedron.LiveTips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfL3nmowibt-FefYeIsuTZsmlaBOyLXbY',
    appId: '1:623278585949:ios:c73a48a4b09f7eaba4b5b4',
    messagingSenderId: '623278585949',
    projectId: 'livetips-app',
    storageBucket: 'livetips-app.firebasestorage.app',
    androidClientId: '623278585949-3p9pa5g2d4tpshm03vt92bjma7min498.apps.googleusercontent.com',
    iosClientId: '623278585949-pgjt0cu5dpo4nlomoujunmlcrn954av7.apps.googleusercontent.com',
    iosBundleId: 'com.mekedron.LiveTips',
  );

}