import 'package:firebase_auth/firebase_auth.dart' show FirebaseAuth;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// The domain that serves Firebase Auth's OAuth handler (`/__/auth/handler`).
///
/// Sign-in flows that hand the user to Google or Apple bounce through this
/// domain, and the user sees it in the popup's address bar — so it says
/// `live.tips` rather than `livetips-app.firebaseapp.com`. It is a custom
/// domain on the `livetips-app` Hosting site; Hosting serves the reserved
/// `/__/auth/*` handler on every custom domain attached to a site.
///
/// This deliberately does NOT live in `firebase_options.dart`: that file is
/// generated by `flutterfire configure` and a hand-edit there would be
/// silently reverted the next time anyone regenerates it. Instead the domain
/// is layered onto the generated options at startup, below.
const kFirebaseAuthDomain = 'auth.live.tips';

/// The web sign-in bridge page on that same domain (see
/// firebase/hosting-public/signin.html and data/firebase/auth_bridge.dart).
/// Same-origin with the `/__/auth/*` handler above — which is the point: the
/// redirect flow only survives Safari's storage partitioning when it starts
/// and finishes on the handler's own origin.
const kAuthBridgeUrl = 'https://$kFirebaseAuthDomain/signin';

/// The generated options with our own auth domain on top.
///
/// The web SDK reads the handler domain from `FirebaseOptions.authDomain`, and
/// only there — `FirebaseAuth.customAuthDomain` throws on web.
FirebaseOptions withCustomAuthDomain(FirebaseOptions options) =>
    options.copyWith(authDomain: kFirebaseAuthDomain);

/// Point the native SDKs at the same handler domain.
///
/// The Android/Apple SDKs ignore `FirebaseOptions.authDomain` (it is a web-only
/// field); they read the domain off the `FirebaseAuth` instance instead. This
/// matters for Sign in with Apple on Android, which has no native sheet and so
/// runs the web flow through the handler (`signInWithProvider`). On iOS/macOS
/// the OS sheets never touch the handler, so this is a harmless no-op there.
///
/// No-op on web, where the setter throws — the options above carry it instead.
void applyCustomAuthDomain(FirebaseAuth auth) {
  if (kIsWeb) return;
  auth.customAuthDomain = kFirebaseAuthDomain;
}
